version: '3.8'
services:

  data-generator:
      build: ./data-generator
      container_name: data-generator
      depends_on:
        - kafka

  zkpr:
    image: confluentinc/cp-zookeeper:5.5.3
    container_name: zkpr
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    healthcheck: { test: nc -z localhost 2181, interval: 1s, start_period: 120s }
  
  kafka:
    container_name: kafka
    image: confluentinc/cp-enterprise-kafka:5.5.3
    depends_on: [zkpr]
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zkpr:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
    - 9092:9092
    healthcheck: { test: nc -z localhost 9092, interval: 1s, start_period: 120s }
    
  materialized:
    image: materialize/materialized:v0.20.0
    container_name: materialized
    command: -w1
    ports:
      - 6875:6875

  mzcli:
    image: materialize/cli
    container_name: mzcli
    depends_on:
      - materialized

  dbt:
    build:
      context: ./dbt
      target: dbt-third-party
      args:
        - build_for=${ARCH}
    container_name: dbt
    ports:
      - 8000:8080
    volumes:
      - ./dbt/profiles.yml:/root/.dbt/profiles.yml
      - ./dbt/:/usr/app/dbt
    stdin_open: true
    tty: true
    depends_on:
      - materialized

  metabase:
    image: ${MIMG}/metabase
    container_name: metabase
    depends_on:
       - materialized
    ports:
      - 3030:3000